// lazyload config

var jp_config = {
  easyPieChart:   [ 'js/charts/easypiechart/jquery.easy-pie-chart.js' ],
  sparkline:      [ 'js/charts/sparkline/jquery.sparkline.min.js' ],
  plot:           [ 'js/charts/flot/jquery.flot.min.js', 
                    'js/charts/flot/jquery.flot.resize.js',
                    'js/charts/flot/jquery.flot.tooltip.min.js',
                    'js/charts/flot/jquery.flot.spline.js',
                    'js/charts/flot/jquery.flot.orderBars.js',
                    'js/charts/flot/jquery.flot.pie.min.js' ],
  slimScroll:     [ 'js/slimscroll/jquery.slimscroll.min.js' ],
  vectorMap:      [ 'js/jvectormap/jquery-jvectormap.min.js', 
                    'js/jvectormap/jquery-jvectormap-world-mill-en.js',
                    'js/jvectormap/jquery-jvectormap-us-aea-en.js',
                    'js/jvectormap/jquery-jvectormap.css' ],
  sortable:       [ 'js/sortable/jquery.sortable.js' ],
  nestable:       [ 'js/nestable/jquery.nestable.js',
                      'js/nestable/nestable.css' ],
  filestyle:      [ 'js/file/bootstrap-filestyle.min.js' ],
  slider:         [ 'js/slider/bootstrap-slider.js',
                      'js/slider/slider.css' ],
  chosen:         [ 'js/chosen/chosen.jquery.min.js',
                      'js/chosen/chosen.css' ],
  TouchSpin:      [ 'js/spinner/jquery.bootstrap-touchspin.min.js',
                      'js/spinner/jquery.bootstrap-touchspin.css' ],
  wysiwyg:        [ 'js/wysiwyg/bootstrap-wysiwyg.js',
                      'js/wysiwyg/jquery.hotkeys.js' ],
  dataTable:      [ 'js/datatables/jquery.dataTables.min.js',
                      'js/datatables/dataTables.bootstrap.js',
                      'js/datatables/dataTables.bootstrap.css' ],
  footable:       [ 'js/footable/footable.all.min.js',
                      'js/footable/footable.core.css' ]
};